[package]
name = "diesel_interaction"
version = "0.1.0"
edition = "2021"

[dependencies]
deadpool-diesel = "0.6.1"
diesel = "2.2.3"
serde = { version = "1.0.209", features = ["derive"] }
thiserror = "1.0.63"
