DROP TABLE abstimmungsergebnisse;
DROP TABLE sonstige_ids;
DROP TABLE ausschussberatungen;
DROP TABLE dokumente;
DROP TABLE gesetzesvorhaben;
DROP TABLE status;
DROP TABLE abstimmungen;
DROP TABLE tops;
DROP TABLE ausschuesse;