# coding: utf-8

"""
    Specification for the Landtagszusammenfasser Project

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from models.autor import Autor
from typing import Optional, Set
from typing_extensions import Self

class Dokument(BaseModel):
    """
    Dokument
    """ # noqa: E501
    titel: Optional[StrictStr] = None
    datum: Optional[date] = None
    url: Optional[StrictStr] = None
    hash: Optional[StrictStr] = None
    zusammenfassung: Optional[StrictStr] = None
    schlagworte: Optional[List[StrictStr]] = None
    autoren: Optional[List[Autor]] = None
    typ: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["titel", "datum", "url", "hash", "zusammenfassung", "schlagworte", "autoren", "typ"]

    @field_validator('typ')
    def typ_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Gesetzesentwurf', 'Beschlussempfehlung', 'Beschluss', 'Protokoll', 'Stellungnahme', 'Sonstiges']):
            raise ValueError("must be one of enum values ('Gesetzesentwurf', 'Beschlussempfehlung', 'Beschluss', 'Protokoll', 'Stellungnahme', 'Sonstiges')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Dokument from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in autoren (list)
        _items = []
        if self.autoren:
            for _item_autoren in self.autoren:
                if _item_autoren:
                    _items.append(_item_autoren.to_dict())
            _dict['autoren'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Dokument from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "titel": obj.get("titel"),
            "datum": obj.get("datum"),
            "url": obj.get("url"),
            "hash": obj.get("hash"),
            "zusammenfassung": obj.get("zusammenfassung"),
            "schlagworte": obj.get("schlagworte"),
            "autoren": [Autor.from_dict(_item) for _item in obj["autoren"]] if obj.get("autoren") is not None else None,
            "typ": obj.get("typ")
        })
        return _obj


