base_url = "http://localhost:8081"
title = "Landtagszusammenfasser"
description = "Ein Klon des Bundestagszusammenfassers für den Landtag Bayerns"
default_language = "de"
compile_sass = true
build_search_index = true

[extra]
