services:
  redis:
    image: redis:latest
    container_name: collector_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    
    environment:
      REDIS_ARGS: "--loglevel=warning --save 60 1"