openapi: 3.0.0
info:
  title: "Specification for the Landtagszusammenfasser Project"
  version: "0.1.0"
paths:
  /api/v1/gesetzesvorhaben/{gsvh_id}:
    get:
      operationId: "gsvh_get_by_id"
      description: "Returns a Gesetzesvorhaben by id"
      parameters:
        - name: "gsvh_id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
        - name: "If-Modified-Since"
          in: "header"
          required: false
          schema:
            type: "string"
            format: "date-time"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/gesetzesvorhaben"
        "304":
          description: "No new changes"
        "404":
          description: "Content not found"
        "500":
          description: "Internal Server Error"
    put:
      operationId: "gsvh_put"
      description: API Access for the Admins without the merge just replacing gsvh
      parameters:
        - name: "gsvh_id"
          in: "path"
          required: true
          description: "The API ID of the GSVH that is to be affected"
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/gesetzesvorhaben"
      responses:
        201:
          description: "Created"
        204:
          description: "Content Unchanged"
        401:
          $ref: "#/components/responses/UnauthorizedError"
      security:
        - apiKey: [] 
  /api/v1/gesetzesvorhaben:
    get:
      operationId: "gsvh_get"
      description: "Returns a filtered List of Gesetzesvorhaben"
      responses:
        "200":
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
        "204":
          description: "No Content found for the specified parameters"
        "304":
          description: "No new changes"
        "416":
          description: "Request Range not satisfiable. Dates before the existence of the BRP or in the future are excluded for example"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

      parameters:
        - name: "if-modified-since"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "date-time"
        - name: "limit"
          in: "query"
          required: false
          schema:
            type: "integer"
        - name: "offset"
          in: "query"
          required: false
          schema:
            type: "integer"
        - name: "initiator-contains-any"
          in: query
          required: false
          description: "If any of the listed Initiators matches the Initiator, it is filtered out"
          schema:
            type: array
            items:
              type: string
        - name: "ggtyp"
          in: query
          required: false
          description: "Gesetzgebungstyp"
          schema:
            $ref: "#/components/schemas/gesetzestyp"
    post:
      operationId: "gsvh_post"
      description: "Pushing a new Gesetzesvorhaben"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/gesetzesvorhaben"
      parameters:
        - name: "collector"
          in: query
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "201":
          description: "Successfully Integrated the Object"
        "400": 
          description: "Bad Request"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "409": 
          description: "Conflict. The Ressource already exists"
        "500":
          description: "Internal Server Error"
      security:
        - apiKey: []
  /api/v1/auth:
    delete:
      operationId: "auth_delete"
      description: "Deletes an API Key from the Database"
      requestBody:
        required: true
        content:
          text/plain: 
            schema:
              type: "string"
              description: "The API Key to be deleted"
      responses:
        "204":
          description: "API Key was deleted successfully"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          description: "API Key not found"
        "500":
          description: "Internal Server Error"
      security:
        - apiKey: [] 
    get:
      operationId: "auth_get"
      description: "Adds a new API Key to the Database"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/create_api_key"
      responses:
        "201":
          $ref: "#/components/responses/ApiKeyCreated"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "500":
          description: "Internal Server Error"
      security:
        - apiKey: [] 
components:
  securitySchemes:
      apiKey:
        description: API key of the Collector
        type: apiKey
        name: X-API-Key
        in: header
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
    ApiKeyCreated:
      description: "API Key was created successfully"
      content:
        text/plain:
          schema:
            type: string
            description: "The API Key that was created"
  schemas:
    create_api_key:
      type: "object"
      required:
        - "scope"
      properties:
        scope:
          type: "string"
          enum:
            - "admin"
            - "collector"
            - "keyadder"
        expires_at:
          type: "string"
          format: "date-time"
          description: "The expiration date of the API Key"
        
    parlament:
      type: "string"
      enum:
        - "BT"
        - "BR"
        - "BV"
        - "EK"
        - "BB"
        - "BY"
        - "BE"
        - "HB"
        - "HH"
        - "HE"
        - "MV"
        - "NI"
        - "NW"
        - "RP"
        - "SL"
        - "SN"
        - "TH"
        - "SH"
        - "BW"
        - "ST"
    gesetzestyp:
      type: "string"
      enum:
        - "bgg-einspruch"
        - "bgg-zustimmung"
        - "bay-parlament"
        - "bay-volk"
        - "sonstig"
      description: "Der Gesetzgebungstrack auf dem wir uns befinden. Zum Beispiel: BundesGesetzGebung - Einspruchsgesetz. Legt fest, welche Stationen hier möglich sind"
    stationstyp:
      type: "string"
      description: "Stationen, die ein Gesetz in verschiedenen Ausformungen durchlaufen kann. Im Prinzip ist die Festlegung auf Prä / Postparlamentarisch arbiträr."
      enum:
        - "preparl-regent" # Referentenentwurf / Regierungsentwurf
        - "preparl-eckpup" # Eckpunktepapier / Parlamentsentwurf
        - "preparl-kabbsl" # Kabinettsbeschluss / Regierungsbeschluss
        - "preparl-vbegde" # Volksbegehren / Diskussionsentwurf
        - "parl-initiativ" # Gesetzesinitiative
        - "parl-ausschber" # Beratung im Ausschuss
        - "parl-vollvlsgn" # Vollversammlung / Lesung
        - "parl-akzeptanz" # Schlussabstimmung & Akzeptanz des Parlaments
        - "parl-ablehnung" # Schlussabstimmung & Ablehnung des Parlaments
        - "parl-ggentwurf" # Gegenentwurf des Parlaments auf abgel. Volksbegehren
        - "postparl-vents" # Volksentscheid nach Parlamentsbeschluss
        - "postparl-gsblt" # Veröffentlichung im Gesetzesblatt
        - "postparl-kraft" # In Kraft getreten
    identifikatortyp:
      type: "string"
      enum:
        - "initdrucks"
        - "vorgnr"
        - "sonstig"
      description: "An identification for the whole process from start to finish"
    dokumententyp:
      type: "string"
      enum:
        - "entwurf"
        - "drucksache"
        - "protokoll"
        - "topliste"
        - "stellungnahme"
        - "sonstig"
      description: "The type of a document"
    dokument:
      type: "object"
      required:
        - "titel"
        - "hash"
        - "typ"
        - "last_mod"
        - "link"
      properties:
        titel:
          type: "string"
        last_mod:
          type: "string"
          format: "date-time"
        link:
          type: "string"
          format: "uri"
        hash:
          type: "string"
        zusammenfassung:
          type: "string"
        schlagworte:
          type: "array"
          items:
            type: "string"
        autorpersonen:
          type: "array"
          items:
            type: "string"
            example: "Ach, Manfred (CSU)"
            description: "The authors of the document if they are persons"
        autoren:
          type: "array"
          items:
            type: "string"
            example: "Staatsregierung, Fraktion die Grünen, Fraktion CDU/CSU"
            description: "The authors of the document if they are not persons, this is to be done at the collector level"
        typ:
          $ref: "#/components/schemas/dokumententyp"
    stellungnahme:
      type: "object"
      required:
        - "dokument"
      properties:
        dokument:
          $ref: "#/components/schemas/dokument"
        meinung:
          type: "integer"
        lobbyregister_link:
          type: "string"
          format: "uri"
    station:
      type: "object"
      required:
        - "datum"
        - "dokumente"
        - "gremium"
        - "parlament"
        - "typ"
        - "betroffene_texte"
      properties:
        datum:
          type: "string"
          format: "date"
        gremium:
          type: "string"
          example: "Ausschuss für Inneres und Gemüseaufläufe"
          description: "Name des Gremiums, das die Station durchgeführt hat oder mit ihr assoziiert ist. Kann ein Ausschuss sein, oder \"Plenum\" oder \"Volk\", etc."
        dokumente:
          type: "array"
          items:
            $ref: "#/components/schemas/dokument"
        betroffene_texte:
          type: "array"
          items:
            type: "string"
            example: "§ 1 Abs. 1 Satz 1"
            description: "The text that is affected by the station"
        link:
          type: "string"
          format: "uri"
        parlament:
          $ref: "#/components/schemas/parlament"
        schlagworte:
          type: "array"
          items:
            type: "string"
            format: "lowercase"
        stellungnahmen:
          type: "array"
          items: 
            $ref: "#/components/schemas/stellungnahme"
        typ:
          $ref: "#/components/schemas/stationstyp"
        trojaner:
          type: "boolean"
    
    gesetzesvorhaben:
      type: "object"
      required:
        - "api_id"
        - "titel"
        - "verfassungsaendernd"
        - "trojaner"
        - "initiatoren"
        - "typ"
        - "stationen"
      properties:
        api_id:
          type: "string"
          format: "uuid"
          example: "123e4567-e89b-12d3-a456-426614174000"
        titel:
          type: "string"
        verfassungsaendernd:
          type: "boolean"
        initiatoren:
          type: "array"
          items:
            type: "string"
            example: "Staatsministerium für Justiz"
            description: "The initiators of the Gesetzesvorhaben. This is meant for institutions or fractions."
        initiator_personen:
          type: "array"
          items:
            type: "string"
            example: "Ach, Manfred (CSU)"
            description: "The authors of the document if they are persons"
        typ:
          $ref: "#/components/schemas/gesetzestyp"
        ids:
          type: "array"
          items:
            $ref: "#/components/schemas/identifikator"
        links:
          type: "array"
          items:
            type: "string"
            format: "uri"
        stationen:
          type: "array"
          items:
            $ref: "#/components/schemas/station"
    identifikator:
      type: "object"
      required:
        - "id"
        - "typ"
      properties:
        id: 
          type: "string"
          example: "123e4567-e"
        typ:
          $ref: "#/components/schemas/identifikatortyp"
    
    response:
      type: "object"
      properties:
        payload: 
          type: "array"
          items:
            $ref: "#/components/schemas/gesetzesvorhaben"