# flavour: 
# - all component objects are required unless marked nullable
# - format: primary_key is for primary key. more than one format: primary_key means an aggregate key. otherwise the whole tabl eis keyed
# - length: length of a string
# - max-length: maximal length of a string
# - `has-id: bool` contains a field named id with the default primary key settings, namely:
# - id:
#      type: integer
#      format: primary_key

openapi: 3.1.0
components:
  schemas:
    gesetzeseigenschaften:
      type: object
      has-id: true
      properties:
        eigenschaft:
          type: string
          max-length: 255

    parlamente:
      type: object
      has-id: true
      properties:
        name:
          type: string
        kurzname:
          type: string
          length: 2
    initiatoren:
      type: object
      has-id: true
      properties:
        name:
          type: string
          nullable: true
        organisation:
          type: string
        url:
          type: string
          nullable: true
          format: url

    dokumententyp:
      type: object
      has-id: true
      properties:
        dokumententyp:
          type: string

    # dinge mit referenzen
    ausschuesse:
      type: object
      has-id: true
      properties:
        name:
          type: string
        parlament:
          $ref: "#/components/schemas/parlamente"
    top-liste-ausschuss:
      type: object
      has-id: true
      properties:
        datum:
          type: string
          format: date-time
        url:
          type: string
          format: url
        ausschuss:
          $ref: "#/components/schemas/ausschuesse"
    top-liste-parlament:
      type: object
      has-id: true
      properties:
        datum:
          type: string
          format: date-time
        url:
          type: string
          format: url
        parlament:
          type: integer
          $ref: "#/components/schemas/parlamente"

    top-parlament:
      type: object
      has-id: true
      properties:
        titel:
          type: string
        top-liste:
          type: integer
          $ref: "#/components/schemas/top-liste-parlamente"

    top-ausschuss:
      type: object
      has-id: true
      properties:
        titel:
          type: string
        top-liste:
          type: integer
          $ref: "#/components/schemas/top-liste-ausschuesse"
      #    Abstimmungen:
      #    Gesetzesstatus:
      #    Gesetzesvorhaben:
      #    Dokumente:
      #    Ausschussberatung:
      #    Gesetztesids:
      #    Abstimmungsergebnisse:
      #    # relations - TODO: necessary?
