# flavour:
# - all component objects are NOT NULL unless marked nullable
# - format: database_key is NOT NULL UNIQUE and if singular and not in $ref, a primary key
# - length: length of a string
# - max-length: maximal length of a string
# - `has-id: bool` contains a field named id with the default primary key settings, namely:
# - id:
#      type: integer
#      format: database_key

openapi: 3.1.0
info:
  title: "Specification for the Landtagszusammenfasser Project"
  version: "0.1.0"
paths:
  /gesetzesvorhaben:
    get:
      description: "Returns a Gesetzesvorhaben by id"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/gesetzesvorhaben"
components:
  schemas:
    cupupdate:
      type: object
      properties:
        msg_id: 
          type: string
        timestamp: 
          type: string
        payload: 
          type: object
          $ref: "#/components/schemas/gesetzesvorhaben"
    cupresponse:
      type: object
      properties:
        msg_id: 
          type: string
        responding_to: 
          type: string

    gesetzesvorhaben:
      type: object
      properties:
        api_id: 
          type: string
        titel:
          type: string
        verfassungsaendernd:
          type: bool
        trojaner:
          type: bool
        federfuehrung:
          type: unbekannt
        initiator:
          type: string
        typ:
          type: string
        links:
          type: unbekannt
        notes:
          type: unbekannt
        stationen:
          type: unbekannt
    station:
      type: object
      

