openapi: "3.0.0"
info:
  title: "Specification for the Landtagszusammenfasser Project"
  version: "0.1.0"
paths:
  /api/v1/gesetzesvorhaben/{gesvh_id}:
    get:
      description: "Returns a Gesetzesvorhaben by id"
      parameters:
        - name: "gesvh_id"
          in: "path"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/gesetzesvorhaben"
  /api/v1/gesetzesvorhaben:
    get:
      description: "Returns a filtered List of Gesetzesvorhaben"
      responses:
        "206":
          description: "partial Content1"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
      parameters:
        - name: "updated_since"
          in: "query"
          required: false
          schema:
            type: "string"
            format: "date"
        - name: "updated_until"
          in: query
          required: false
          schema:
            type: "string"
            format: "date"
        - name: "limit"
          in: query
          required: false
          schema:
            type: "integer"
            minimum: 1
            maximum: 100
        - name: "offset"
          in: query
          required: false
          schema:
            type: "integer"
            minimum: 0
        - name: "parlament"
          in: query
          required: false
          schema:
            $ref: "#/components/schemas/parlament"
    post:
      description: "Pushing a new Gesetzesvorhaben"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/gesetzesvorhaben"
      parameters:
        - name: "collector"
          in: query
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        "201":
          description: "Successfully Created or Integrated the Object"
components:
  schemas:
    parlament:
      type: "string"
      enum:
        - "BT"
        - "BR"
        - "BV"
        - "EK"
        - "BB"
        - "BY"
        - "BE"
        - "HB"
        - "HH"
        - "HE"
        - "MV"
        - "NI"
        - "NW"
        - "RP"
        - "SL"
        - "SN"
        - "TH"
        - "SH"
        - "BW"
        - "ST"
    gesetzestyp:
      type: "string"
      enum:
        - "bgg-einspruch"
        - "bgg-zustimmung"
        - "volksgg"
        - "landgg"
        - "sonstig"
    stationstyp:
      type: "string"
      enum:
        - "preparl-regent" # Referentenentwurf / Regierungsentwurf
        - "preparl-eckpup" # Eckpunktepapier / Parlamentsentwurf
        - "preparl-kabbsl" # Kabinettsbeschluss / Regierungsbeschluss
        - "preparl-vbegde" # Volksbegehren / Diskussionsentwurf
        - "parl-initiativ" # Gesetzesinitiative 
        - "parl-ausschber" # Beratung im Ausschuss
        - "parl-vollvlsgn" # Vollversammlung und Lesung
        - "parl-schlussab" # Schlussabstimmung
        - "parl-akzeptanz" # Akzeptanz des Parlaments
        - "parl-ablehnung" # Ablehnung des Parlaments
        - "parl-ggentwurf" # Gegenentwurf des Parlaments auf abgel. Volksbegehren
        - "postparl-vents" # Volksentscheid nach Parlamentsbechlus
        - "postparl-gsblt" # Veröffentlichung im Gesetzesblatt
        - "postparl-kraft"  # In Kraft getreten
    identifikatortyp:
      type: "string"
      enum:
        - "drucksnr"
        - "vorgnr"
        - "sonstig"
    dokumententyp:
      type: "string"
      enum:
        - "entwurf"
        - "drucksache"
        - "protokoll"
        - "stellungnahme"
        - "sonstig"
    dokument:
      type: "object"
      required:
        - "titel"
        - "hash"
        - "typ"
        - "zeitpunkt"
        - "url"
      properties:
        titel:
          type: "string"
        zeitpunkt:
          type: "string"
          format: "date"
        url:
          type: "string"
          format: "uri"
        hash:
          type: "string"
        zusammenfassung:
          type: "string"
        schlagworte:
          type: "array"
          items:
            type: "string"
        autoren:
          type: "array"
          items:
            type: "string"
            example: "Staatsregierung"
        typ:
          $ref: "#/components/schemas/dokumententyp"
    stellungnahme:
      type: "object"
      required:
        - "dokument"
      properties:
        dokument:
          $ref: "#/components/schemas/dokument"
        meinung:
          type: "integer"
        lobbyregister_url:
          type: "string"
          format: "uri"
    station:
      type: "object"
      required:
        - "zeitpunkt"
        - "dokumente"
        - "gremium"
        - "parlament"
        - "typ"
      properties:
        zeitpunkt:
          type: "string"
          format: "date"
        gremium:
          type: "string"
          example: "Ausschuss für Inneres und Gemüseaufläufe"
          description: "Name des Gremiums, das die Station durchgeführt hat oder mit ihr assoziiert ist. Kann ein Ausschuss sein, oder \"Plenum\" oder \"Volk\", etc."
        dokumente:
          type: "array"
          items:
            $ref: "#/components/schemas/dokument"
        url:
          type: "string"
          format: "uri"
        parlament:
          $ref: "#/components/schemas/parlament"
        schlagworte:
          type: "array"
          items:
            type: "string"
            format: "lowercase"
        stellungnahmen:
          type: "array"
          items: 
            $ref: "#/components/schemas/stellungnahme"
        typ:
          $ref: "#/components/schemas/stationstyp"
        trojaner:
          type: "boolean"
    gesetzesvorhaben:
      type: "object"
      required:
        - "api_id"
        - "titel"
        - "verfassungsaendernd"
        - "trojaner"
        - "initiatoren"
        - "typ"
        - "stationen"
      properties:
        api_id:
          type: "string"
          format: "uuid"
          example: "123e4567-e89b-12d3-a456-426614174000"
        titel: 
          type: "string"
        verfassungsaendernd:
          type: "boolean"
        initiatoren:
          type: "array"
          items:
            type: "string"
            example: "Staatsministerium für Justiz"
        typ:
          $ref: "#/components/schemas/gesetzestyp"
        ids:
          type: "array"
          items:
            $ref: "#/components/schemas/identifikator"
        links:
          type: "array"
          items:
            type: "string"
            format: "uri"
        stationen:
          type: "array"
          items:
            $ref: "#/components/schemas/station"
    identifikator:
      type: "object"
      required:
        - "id"
        - "typ"
      properties:
        id: 
          type: "string"
          example: "123e4567-e"
        typ:
          $ref: "#/components/schemas/identifikatortyp"
    
    response:
      type: "object"
      properties:
        payload: 
          type: "array"
          items:
            $ref: "#/components/schemas/gesetzesvorhaben"