name: Testing the LTZF Project

on: [push, pull_request]

jobs:
  database_tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ltzf-user
          POSTGRES_PASSWORD: ltzf-pass
          POSTGRES_DB: ltzf
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Generate OAPI Code
        run: sh oapi_gen.sh

      - name: Run cargo tests
        working-directory: database/
        run: cargo test
        env:
          DATABASE_URL: postgres://ltzf-user:ltzf-pass@localhost:5432/ltzf
          SQLX_OFFLINE: true

  collector_tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Generate OAPI Code
        run: sh oapi_gen.sh

      - name: Run pytest
        working-directory: collector/
        run: poetry install && poetry run pytest